---
title: "Hausaufgabe 2"
author: "Team 4 (Milena Mensching, Justus Weyers)"
date: "`r Sys.Date()`"
output: 
  pdf_document: 
    keep_tex: yes
---

# Aufgabe 1
**Sie wiegen mit einer digitalen Waage, deren kleinste Schrittweite (d.h. Auflösung) 0,1
g beträgt, einen Apfel. Der Apfel wiegt laut Anzeige 120,0 g. Stellen Sie sich vor, nach
der Messung stellen Sie fest, dass der Tisch auf dem die Waage steht, schief steht.
Die Schieflage beträgt ca. 1-2 Grad.**

*  **Berechnen Sie welche systematische Abweichung dadurch entsteht.**
*  **Ist es richtig anzunehmen, dass die Messung dennoch korrekt war und die Messung aufgrund der Messunsicherheiten als richtig angenommen werden
kann?**

**geg.:** Bestwert Masse $m = 120,0$; Geräteart: digital; Auflösung $a=0,1g$. Als Winkel $\alpha$ wird der Extremfall gewählt, bei dem die Neigung 2° beträgt.

**ges.:** Systematische Abweichung $e$

**Rechnung:**

Bei einer schiefen Ebene nimmt der Betrag der Normalkraft um den Kosinus des Neigunswinkels ab:
$$e = m*(1-cos(\alpha)) = 120,0g*(1-cos(2)) = 0,073g$$

Die Messunsicherheit beträgt:
$$ u = \frac{a}{2\sqrt{3}} \Rightarrow \frac{0,1g}{2\sqrt{3}} = 0,029g$$
Damit ist die Systematische Abweichung größer, als die Messunsicherheit. Das Ergebnis ist also im Rahmen der Messunsicherheit nicht korrekt.

# Aufgabe 2:
**Es wurden 3 verschiedene Techniken genutzt, um den Durchmesser und
Umfang eines runden Objektes zu messen und daraus experimentell die
Größe $\pi$ zu bestimmen. Methode 1 ergibt: 3,133 ± 0,007, Methode 2 3,1609 ±
0,0002 und Methode 3 war 3,14 ± 0,03. Welche der 3 Methoden ist die
präziseste? Begründen Sie Ihre Antwort.**

Methode 2 liefert das präziseste Ergebnis. Dieses wurde hier auf vier Nachkommastellen genau angegeben. Die hohe Präzision sagt allerdings nichts über die Richtigkeit des Ergebnisses aus.

# Aufgabe 4
**Tom hängt drei Gewichte an eine Feder. Er benutzt eine Waage (die
Messunsicherheit des Gerätes $u_{Waage}$ beträgt 0,05g, die Auflösung der Waage
beträgt 0,1g) um die drei Massen einmalig zu bestimmen. Tom liest auf der
Waage folgenden Werte für die Massen ab:**

* $M_1= 30,2 g$
* $M_2= 9,8 g$
* $M_3= 5,1 g$

**Wie schwer ist die gesamte Masse? Vergessen Sie nicht die
Messunsicherheit dazu.**

Berechnung der Skalen-Unsicherheit $u_{Skala}$ mit $a=0,1g$:
$$u_{Skala} = \frac{a}{2\sqrt{6}} = \frac{0,1g}{2\sqrt{6}}$$
Berechnung der Geräteunsicherheit $u_{Gerät}$:
$$u_{Gerät} =\pm \sqrt{u_{Skala}^2+u_{Waage}^2} =\pm \sqrt{(\frac{0,1}{2\sqrt{6}})^2+(0,05)^2}g = \pm 0,054g$$

Formel für die Berechnung der Gesamtmasse $m_{ges}$:
$$m_{ges} = m_1+m_2+m_3$$

Berechnung der Messunsicherheit $u$:
\begin{align*}
\begin{split}
u&=\pm \sqrt{(\frac{\partial m_{ges}}{\partial m_1}*u_{Gerät})^2+(\frac{\partial m_{ges}}{\partial m_2}*u_{Gerät})^2+(\frac{\partial m_{ges}}{\partial m_3}*u_{Gerät})^2}\\
 &= \sqrt{((1+m_2+m_3)*u_{Gerät})^2+((m_1+1+m_3)*u_{Gerät})^2+((m_1+m_2+1)*u_{Gerät})^2}\\
\Rightarrow &= \sqrt{((1+9,8+5,1)*0,054)^2+((30,2+1+5,1)*0,054)^2+((30,2+9,8+1)*0,054)^2}\\
&= 3,1g\\
\end{split}
\end{align*}

Die Gesamtmasse $m_{ges}$ beträgt also:
$$m_{ges}=((30,2+9,8+5,1)\pm 3,1)g = (45,1 \pm 3,1)g$$
# Aufgabe 6

**Jo will die Periodendauer T eines Pendels experimentell bestimmen. Jo
entscheidet statt einer einzelnen Periode 20 Perioden mit der Stoppuhr zu
messen. Wie kann Jo die Periodendauer T und ihre Messunsicherheit
bestimmen?
Wenn Sie jetzt die Ergebnisse dieser Übung reflektieren, würden Sie sagen
dass es um die Periodendauern eines Pendels zu bestimmen, besser ist
mehrere Perioden zu messen oder wenige?**

Es handelt sich bei diesem Vorgehen um eine Auswertung der Daten nach Typ-A (GUM), also einen statistschen Ansatz zur abschätzung der Messunsicherheit.

Die Verteilung der Messergebnisse wird als normalverteilt angenommen (Gauss-Verteilung).

Jo kann den Mittelwert $\overline{T}$ aus allen 20 Periodendauern berechnen.
$$\overline{T} = \frac{1}{n}\sum \limits_{i=1}^nT_i$$

* $\bar{T}$: Gemittelte Periodendauer
* $T_i$: Periodendauer der $i$-ten Messung
* $n$: Anzahl von Perioden

Um die Streuung der Messwerte einschätzen zu können wird dann die Standardabweichung berechnet:
$$\sigma_x = \sqrt{\frac{1}{n-1} \sum_{i=1}^n (T_i - \overline{T})^2}$$
Diese sagt aus, wie stark die Ergebnisse um den Mittelwert streuen. Da der Mittelwert für eine Teilmenge der Messungen ebenfalls streuen kann wird auch die Standardabweichung des Mittelwertes berechnet:
$$\sigma_{\overline{T}}=\frac{\sigma_x}{\sqrt{n}}$$
Diese ist für normalverteilte Stichproben der entscheidende Parameter. "Dieser gibt das Intervall an, in dem sich 68,3% aller Mittelwerte, noch folgender Messreihen befinden werden" [Skript: "Umgang mit Messunsicherheiten Teil 1", S.5]. Die **Standardmessunsicherheit** der n-mal geessenen Periodendauer lässt sich so statistisch abschätzen [ebd.].

Das Messergebnis wird mit $\overline{T} \pm \sigma_{\overline{T}}$ angegeben.

Aus der Formel für die Standardabweichung des Mittelwertes wird ersichtlich, dass für eine größere Anzahl von Messungen n die Standardabweichung des Mittelwertes kleiner wird.

# Aufgabe 7:

**Wieso ist die Messung der Periodendauer eines Pendels präziser, wenn man
die Stoppuhr beim Punkt der maximalen Geschwindigkeit des Pendels und
nicht beim Punkt der minimalen Geschwindigkeit startet (bzw. stoppt)?
Hinweis: denken Sie an die Reaktionszeit einer Person.**

Vermutlich ist das der Unsicherheit eines Menschan bei der Festlegung auf einen Zeitpunkt der maximalen Auslenkung des Pendels geschuldet. Die Unsicherheit besteht dann darin, dass es schwierig ist, in dem vergleichsweise langen Zeitraum, den das Pendel in der maximalen Auslenkung und anderen Positionen der Fast-Maximalauslenkung verbringt, die Stoppuhr richtig zu betätigen. Die Periodendauer kann dann auf zufällige Art und Weise als zu kurz oder zu lang angegeben werden. Dieser Umstand muss nicht zu einer größeren systematischen Abweichung führen, allerdings zu einer kleineren Präzision. Der Durchgang durch die minimale Auslenkung ist dagegen vergleichsweise gut auszumachen und anzugeben. Die Reaktionszeit ist nachträglich aber in beiden Fällen zu berücksichtigen. 

Es wären aber auch noch präzisere Methoden zur Bestimmung der Periodendauer denkbar. Beispielsweise die Aufnahme des schwingenden Pendels mit einer Kamera mit einer möglichst hohen zeitlichen Auflösung (Bildwiederholungsrate). Am Computer ließen sich dann der Zeitpunkt des Einzelbildes der minimalen Auslenkung bestimmen. Die Reaktionszeit würde in diesem Falle praktisch wegfallen.
