---
title: "Brownsche Molekülbewegung"
author: "Milena Mensching und Justus Weyers"
date: "`r Sys.Date()`"
output: pdf_document
---

# Simulation

# Experiment

## Thema

## Material

```{=tex}
\begin{itemize}
\item{Mikropartikel (Polystyrol) Suspension in Wasser}
\item{Lichtmikroskop mit Objektträger}
\item{Deckplättchen
\item{Thermometer}
\item{Zur Messung und Auswertung wurden folgende Computerprogramme benutzt: ThorCam, Tracker & SciDAVis}
\end{itemize}
```
## Versuchsaufbau und Durchführung

AUf einen Objektträger wird ein Tropfen einer Mikropartikel (Polystyrol) Suspension in Wasser gegeben. Zwei Deckplättchen werden neben den Tropfen, und eines mittig auf die anderen beiden positioniert und unter das Mikroskop gelegt. Die Polystyrolpartikel werden scharf gestellt. Als Vergrößerung wird 40/0.65 gewählt. Mit Hilfe einer Mikroskopkamera und des Programms "ThorCam" wird die Projektion auf dem Bildschirm sichtbar.

Nach Aufnehmen der Messreihe wird die Temperatur gemessen. Diese betrug 21,7°C. Danach wird mit Hilfe des Programms "Tracker" die Position des Teilchens ausgewertet. Dafür wird in einem Datensatz von 100 Bildern das "Teilchen of interest" mit dem Cursor markiert.

## Fehlerbetrachtung

Die größste Ungenauigkeit entsteht bei der Auswertung der Bilder, bzw. beim Markieren des zu beobachtenden Teilchens. Es kann nicht garantiert werden, dass der CUrsor allzeit perfekt mittig auf dem Teilchen liegt.

## Beobachtungen

```{r}
Data <- read.csv("Daten/styrolpartikel/AVI1.csv", header = T, sep =";", dec = ",")
colnames(Data) <- Data[1,]
Data <- Data[2:nrow(Data),]

head(Data)

plot(x=Data$x, y= Data$y)

install.packages("tidyverse")
library(tidyverse)
typeof(Data$x)

x <- rep(NA, nrow(Data))
for (i in 1:nrow(Data)){
  print(Data$x[i][1:5])
}
x
```
## Auswertung

## Interpretation
